Support extended functional components
vuejs/vue-test-utils pull request #1055
Opened 2018-12-04 22:17 UTC by kellym

This fixes an issue where a component that extends another functional component is not treated as a functional component by vue-test-utils.

2018-12-04 22:41 UTC, kellym commented
I guess an example would be helpful. I ran into this via this issue: 

```
// MyFunctionalComponent
export default {
  extends: BaseFunctionalComponent
}
```
```
// BaseFunctionalComponent
export default {
  functional: true
}
```

When mounting `MyFunctionalComponent`, it would throw an error when using `context` saying it wasn't functional.

2018-12-05 15:46 UTC, kellym commented
Just updated to account for `mixins`, since those are inherited similarly to `extends`.

2018-12-06 18:55 UTC, eddyerburgh requested changes
The change looks great, but can you add two test cases for the change? That way we avoid regressions!

2018-12-06 19:44 UTC, kellym commented
You know, I had tests in the really old branch I originally wrote this, but I couldn't find where the `isVueComponent` tests, etc, went since I rebased.  Where should I put the tests?

2018-12-07 05:45 UTC, eddyerburgh commented
You could put them in `wrapper/find.spec.js`

2018-12-10 21:54 UTC, kellym commented
I ended up adding them in what seemed to be more targeted:  `test/specs/mounting-options/context.spec.js`.

2018-12-12 12:57 UTC, eddyerburgh commented
Yes that's a more relevant file!

Can you also make sure the tests test that it renders with the correct context, maybe by trying to call a method that will only exist if the context is passed correctly

2019-03-22 21:23 UTC, kellym commented
Sorry for the delay on this PR. I think at some point during writing tests I found that this solution doesn't solve it across the board -- there was still a scenario where it was not treated as a functional component.

2020-01-03 07:00 UTC, lmiller1990 commented
Hey @kellym - sorry for the slow reply, do you have an example of the case that this _doesn't_ cover by any chance?

2020-03-20 12:21 UTC, closed without merging