Update common-tips.md
vuejs/vue-test-utils pull request #1167
Opened 2019-03-04 08:38 UTC by nachao

汉化不完整，导致用例会产生歧义。

2019-03-04 09:54 UTC, kazupon commented
ping @Jinjiang

2019-03-05 11:06 UTC, Jinjiang requested changes
近期的翻译更新都倾向于不翻译代码里的字符串了，只翻译注释。所以这里的改动并没有必要了。
谢谢

2019-03-05 11:07 UTC, Jinjiang commented
@kazupon I think the change is not necessary.
Thanks.

2019-03-05 14:15 UTC, kazupon commented
@Jinjiang 
Thanks reviewing!

>I think the change is not necessary.

@nachao 
close for this reason.
Thank you for your feedback.

2019-03-05 14:15 UTC, closed without merging