docs: Translate part of the test case name
vuejs/vue-test-utils pull request #1174
Opened 2019-03-08 12:54 UTC by xuhongbo

翻译部分中文测试用例名称

2019-03-09 06:13 UTC, xuhongbo commented
ping @Jinjiang

2019-03-10 18:35 UTC, Jinjiang requested changes
Same to #1167 changes are not necessary.
Thanks.

2019-03-11 02:30 UTC, xuhongbo commented
> Same to #1167 changes are not necessary.
> Thanks.

但是我看现在用例的名称，现在既有中文，又有英文 感觉有点不统一 @Jinjiang

2019-03-11 07:36 UTC, Jinjiang commented
翻译成了中文的都是比较早期翻译的，类似的情况别的库的文档里也有，包括官网里的例子，现在都统一不翻译了。你看到的翻译过的地方我也在考虑要不要找个机会恢复回英文，和其它大多数地方保持一致。
谢谢

2019-03-11 07:49 UTC, xuhongbo commented
> 翻译成了中文的都是比较早期翻译的，类似的情况别的库的文档里也有，包括官网里的例子，现在都统一不翻译了。你看到的翻译过的地方我也在考虑要不要找个机会恢复回英文，和其它大多数地方保持一致。
> 谢谢

@Jinjiang 感谢您的耐心解答

2019-03-11 07:49 UTC, closed without merging