docs(zh): updated
vuejs/vue-test-utils pull request #1194
Opened 2019-03-25 09:12 UTC by Jinjiang

Ref: https://github.com/vuejs/vue-test-utils/compare/6c3e754...f4ea3fd
/ping @Justineo 
Thanks

2019-04-17 14:30 UTC, kazupon commented
@Justineo Can you review this PR?

2019-04-23 09:43 UTC, Justineo requested changes

2019-04-23 09:43 UTC, Justineo commented on docs/zh/api/options.md
> +当通过 `mount` / `shallowMount` 挂载时，这些选项将会合并入组件现有的选项中
```suggestion
当通过 `mount` / `shallowMount` 挂载时，这些选项将会合并入组件现有的选项中。
```

2019-04-23 10:00 UTC, Justineo approved these changes

2019-04-23 10:21 UTC, merged