docs: update Russian translation
vuejs/vue-test-utils pull request #1215
Opened 2019-04-21 14:59 UTC by sh7dm

Update some outdated Russian translations, checked all of them. Fixed some type in Russian docs.

2019-04-23 07:02 UTC, kazupon commented
/ping @Alex-Sokolov 
Can you review this PR?

2019-04-24 07:24 UTC, Alex-Sokolov requested changes

2019-04-24 07:24 UTC, Alex-Sokolov commented on docs/ru/api/options.md
> +чтобы удалить отрисованные элементы из документа и удалить экземпляр компонента.
Remove extra line break

Лишний перенос строки

2019-04-24 07:24 UTC, Alex-Sokolov commented on docs/ru/api/options.md
> +Кроме опций, описанных ниже, обЪект `options` может содержать любую опцию, которую можно указать при вызове `new Vue ({ /* опции здесь */ })`.
Ъ — change to lowercase

Ъ — стоит регистр изменить на нижний

2019-04-24 07:24 UTC, Alex-Sokolov commented on docs/ru/api/options.md
> +Эти опции будут объединены с сущесвующими опциями компонента при монтировании с помощью `mount` / `shallowMount`
сущесвующими — Typo

сущесвующими — Опечатка

2019-04-24 07:24 UTC, Alex-Sokolov commented on docs/ru/api/wrapper/destroy.md
> +Если опция `attachToDocument` была `true` при монтировании, DOM жлементы компонента
жлементы — typo

жлементы — опечатка

2019-04-24 07:24 UTC, Alex-Sokolov commented on docs/ru/api/wrapper/destroy.md
> +будут также удалены из документа.
Extra line break

Лишний перенос строки

2019-04-24 07:25 UTC, Alex-Sokolov commented
@sh7dm Thanks for PR! :) Can you commit fixes to my comments?

2019-04-25 10:15 UTC, sh7dm commented
@Alex-Sokolov Thanks!
@Alex-Sokolov Спасибо!

2019-04-25 10:16 UTC, sh7dm commented
Could you re-review it?

2019-04-26 07:11 UTC, Alex-Sokolov approved these changes

2019-04-26 07:11 UTC, Alex-Sokolov commented
@sh7dm Thanks!
@kazupon Done :)

2019-04-26 10:49 UTC, kazupon commented
@Alex-Sokolov Thanks!

2019-04-26 10:49 UTC, merged