Template query selector support
vuejs/vue-test-utils pull request #1320
Opened 2019-10-14 14:16 UTC by earnubs

Handle selectors passed in the `template` option of the Vue instance (https://vuejs.org/v2/api/#template), currently test-utils gives an unfriendly error as the selector is passed as a template string:

```
browser.js:954 [Vue warn]: Error compiling template:

#foo

- Component template requires a root element, rather than just text.
```

Repro here: https://jsfiddle.net/earnubs/c5d2mea7/

2019-12-16 11:18 UTC, dobromir-hristov commented
A few notes:
1. I have not thought about this case tbh, but I can see it being useful for people not using bundlers.
2. lets remove the dist files, we can generate these on release.
3. The test has a check, you can use the `itDoNotRunIf`.
4. I am not sure how good of an idea it is to use `document` or `window` directly like that.

2019-12-16 11:33 UTC, lmiller1990 commented
This is a great addition! Nice job.

As pointed out, try something like `itDoNotRunIf(TEST_ENV === "node")`. Full API for `conditional-specs`: https://github.com/eddyerburgh/conditional-specs.

Your suspicion about mutating window/document were correct @dobromir-hristov. For this reason, before and after each test, the window variable is reset, to keep things clean. See [here](https://github.com/vuejs/vue-test-utils/blob/3115396f9b2e991b290ce8c7c7b27218e368d70e/test/specs/mount.spec.js#L21).

I'm happy to approve this once

- [ ] use `itDoNotRunIf`
- [ ] remove `dist` files

Are you able to make these changes, @earnubs ?

2019-12-16 11:34 UTC, lmiller1990 requested changes

2019-12-16 11:34 UTC, lmiller1990 commented on test/specs/mount.spec.js
> +      !(navigator.userAgent.includes && navigator.userAgent.includes('node.js'))
see comments

2019-12-16 12:26 UTC, earnubs commented
Test is failing, I'll take a look at this tonight when I have a bit more time.

2019-12-17 00:02 UTC, lmiller1990 approved these changes

2019-12-17 07:37 UTC, merged