Guide on using vue test utils without a build step
vuejs/vue-test-utils pull request #1373
Opened 2019-12-16 11:17 UTC by lmiller1990

Add a guide explaining how to use Vue test utils without a test runner (just Node.js).

resolves #1192

2019-12-16 18:01 UTC, JessicaSachs requested changes
Great guide. There’s an incorrect link, but that’s it.

2019-12-16 18:01 UTC, JessicaSachs commented on docs/guides/usage-without-a-build-step-node.md
> +While it is common to build Vue applications using tools [Webpack](https://jestjs.io/) to bundle the application, `vue-loader` to leverage Single File Components, and [Jest](https://jestjs.io/) to wr
The link to webpack is incorrect.

2019-12-17 07:57 UTC, dobromir-hristov approved these changes

2019-12-17 09:30 UTC, afontcu approved these changes

2019-12-18 01:19 UTC, JessicaSachs approved these changes

2019-12-18 01:20 UTC, merged