#1526: Fixed missing import of the Cheerio type
vuejs/vue-test-utils pull request #1527
Opened 2020-05-04 16:50 UTC by unicrus

**What kind of change does this PR introduce?** (check at least one)

- [x] Bugfix
- [ ] Feature
- [ ] Code style update
- [ ] Refactor
- [x] Build-related changes
- [ ] Other, please describe:

**Does this PR introduce a breaking change?** (check one)

- [ ] Yes
- [x] No

If yes, please describe the impact and migration path for existing applications:

**The PR fulfills these requirements:**

- [x] It's submitted to the `dev` branch.
- [x] When resolving a specific issue, it's referenced in the PR's title (e.g. `fix #xxx[,#xxx]`, where "xxx" is the issue number)
- [x] All tests are passing: https://github.com/vuejs/vue-test-utils/blob/dev/.github/CONTRIBUTING.md#development-setup
- [ ] New/updated tests are included

If adding a **new feature**, the PR's description includes:

- [ ] A convincing reason for adding this feature (to avoid wasting your time, it's best to open a suggestion issue first and wait for approval before working on it)

**Other information:**

2020-05-06 10:09 UTC, lmiller1990 commented
Are you sure this is necessary? I am not seeing this typing error in `dev` in VSCode.

2020-05-06 10:17 UTC, unicrus commented
> Are you sure this is necessary? I am not seeing this typing error in `dev` in VSCode.
Yes. I cannot compile my project, which depends on @vue/server-test-utils, because of this.

And VS Code shows the error:
![image](https://user-images.githubusercontent.com/2191338/81166122-7e4a8980-8f93-11ea-94dc-bd8f9d2d75a5.png)

2020-05-06 12:22 UTC, lmiller1990 commented
I don't get this one. 

<img width="1136" alt="image" src="https://user-images.githubusercontent.com/19196536/81176113-00fd3400-8fe8-11ea-930b-d3d20fa98f7a.png">

I will ask someone with more TS knowledge, please wait a moment.

2020-05-06 12:25 UTC, unicrus commented
Probably, you have Cheerio registered globally somehow.

2020-05-06 12:36 UTC, pikax commented
@unicrus works fine for me, can you run `yarn --check-files`?

If that doesn't work, can you check if you have the file `node_modules/@types/cheerio/index.d.ts`?

2020-05-08 10:48 UTC, unicrus commented
@lmiller1990, @pikax please take a look at the example to reproduce the bug: https://github.com/unicrus/vue-server-test-utils-1526.

TypeScript is a strictly typed language, all types must be defined before usage.

2020-05-08 11:03 UTC, pikax commented
`@vue/server-test-utils` has `cheerio` and `@types/cheerio` has dependencies.

Your repo is overriding the `types` in tsconfig.json
```ts
  "types": [
      "@types/node"
    ]
```

Making typescript only load those types! As per the documentation

```
If types is specified, only packages listed will be included
```


If you remove the types option, it will pick up the types by default. Or you can add Cheerio to your types
```
    "types": [
      "@types/node", 
      "@types/cheerio"
    ]
```

2020-05-08 11:24 UTC, unicrus commented
That's right. But @vue/test-utils does not rely on global types for everything else, like Vue or Vuex. They're explicitly imported. Why should Cheerio be different? It's not a well-known type.

2020-05-14 16:44 UTC, seyfer commented
I cannot build my TS project because of this issue.

https://github.com/vuejs/vue-test-utils/issues/571#issuecomment-628749257

2020-05-14 22:25 UTC, lmiller1990 commented
@pikax any down sides to merge this types PR? I don't know TS super well, seems like it's blocking a few people - I don't see any downsides to the extra import (right?)

2020-05-14 22:35 UTC, pikax requested changes

2020-05-14 22:35 UTC, pikax commented on package.json
> +    "test:types": "tsc -p packages/test-utils/types && tsc -p packages/server-test-utils/types --allowSyntheticDefaultImports"
You don't need to change this line

2020-05-14 22:35 UTC, pikax commented on packages/server-test-utils/types/index.d.ts
> +import Cheerio from 'cheerio'
```suggestion
import * as Cheerio from 'cheerio'
```

2020-05-14 22:42 UTC, pikax commented
Sorry, got side tracked and this went under the radar.

My requested changes are not required, is just less code, if you want you can merge this.

The explanation is, cheerio types don't expose a default import, but when you import with typescript it expects the default module, the flag on the the script tells typescript to basically do `import * as ` if no default module is available.

2020-05-14 22:42 UTC, lmiller1990 commented
@unicrus if you can make those changes we can get this merged and released - we have a release in a day or two.

2020-05-15 08:30 UTC, unicrus commented on packages/server-test-utils/types/index.d.ts
> +import Cheerio from 'cheerio'
Done

2020-05-15 08:31 UTC, unicrus commented
@lmiller1990, done. Thanks.

2020-05-15 08:31 UTC, pikax approved these changes

2020-05-16 00:33 UTC, merged