docs(zh): updated api docs 950763f...a0b40f0
vuejs/vue-test-utils pull request #1568
Opened 2020-06-07 16:51 UTC by Jinjiang

**What kind of change does this PR introduce?** (check at least one)

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update
- [ ] Refactor
- [ ] Build-related changes
- [x] Other, please describe: Chinese docs translation update

**Does this PR introduce a breaking change?** (check one)

- [ ] Yes
- [x] No

If yes, please describe the impact and migration path for existing applications:

**The PR fulfills these requirements:**

- [ ] It's submitted to the `dev` branch.
- [ ] When resolving a specific issue, it's referenced in the PR's title (e.g. `fix #xxx[,#xxx]`, where "xxx" is the issue number)
- [ ] All tests are passing: https://github.com/vuejs/vue-test-utils/blob/dev/.github/CONTRIBUTING.md#development-setup
- [ ] New/updated tests are included

If adding a **new feature**, the PR's description includes:

- [ ] A convincing reason for adding this feature (to avoid wasting your time, it's best to open a suggestion issue first and wait for approval before working on it)

**Other information:**

Ref: 950763f...a0b40f0
/cc @Justineo

2020-06-09 17:31 UTC, Justineo requested changes

2020-06-09 17:31 UTC, Justineo commented on docs/zh/api/config.md
> +关闭废弃警告。
这个描述感觉是反的……

2020-06-09 17:31 UTC, Justineo commented on docs/zh/api/options.md
> +由于该特性内部实现的原因，这里的插槽内容不得不返回一个根元素，即使一个作用域插槽是允许返回一个元素数组的。
“不得不”改成“必须”是不是更好一些

2020-06-09 17:31 UTC, Justineo commented on docs/zh/api/options.md
> +指定一个 HTMLElement 或定位到一个 HTML Element 的 CSS 选择器字符串，组件将会被完全挂载到文档中的这个元素。
HTMLElement & HTML 元素？

2020-06-09 17:31 UTC, Justineo commented on docs/zh/api/options.md
> +remove the rendered elements from the document and destroy the component instance.
删

2020-06-09 17:31 UTC, Justineo commented on docs/zh/api/options.md
> +当挂载到这个 DOM 时，你需要在测试的结尾调用 `wrapper.destroy()` 以将该元素从文档中移除，并销毁该组件实例。
当要挂载到 DOM 时

2020-06-09 17:31 UTC, Justineo commented on docs/zh/api/wrapper/findAllComponents.md
> +未所有匹配的 Vue 组件返回一个 [`WrapperArray`](../wrapper-array/)。
未->为

2020-06-10 00:58 UTC, Jinjiang commented on docs/zh/api/config.md
> +关闭废弃警告。
原文是“Turn off deprecation warnings.”示例是设为 false

2020-06-10 01:20 UTC, Jinjiang commented on docs/zh/api/config.md
> +关闭废弃警告。
我建议先按照原文翻译，同时我们可以和团队讨论更好的英文描述

2020-06-10 02:28 UTC, Justineo approved these changes

2020-06-10 19:09 UTC, afontcu commented on docs/zh/api/config.md
> +关闭废弃警告。
Hi! Just in case, I set up a PR to update the definition of `showDeprecationWarnings`, in case you want to _be ahead_: https://github.com/vuejs/vue-test-utils/pull/1575 :)

2020-06-11 09:47 UTC, maicss commented
两位大佬，需要帮忙吗，我看你们一次翻译这么多……
如果不需要的话，能不能帮我一哈？
https://github.com/vuejs/vue-test-utils/issues/1566

2020-06-11 15:32 UTC, Jinjiang commented
@maicss 多谢。我们确实需要更多人参与到翻译工作中来。我们目前的维护方式是把最后一次翻译时 dev 分支的 commit hash 记录下来，然后用这个 hash 定期比较最新的 dev 分支。当发现 docs 目录变化比较可观的时候做一次翻译同步，类似这个 PR。同样的方式也会用在 vuex, vue-router, vue-loader 等别的仓库，也包括中文官网。
VTU 前段时间确实疏于同步了，而且在 1.0 之前琐碎的改动比较多，所以这次的翻译量比较大。

(translation: for short it's talking about how to contribute Chinese docs translation, not about the content in this PR.)

2020-06-11 15:55 UTC, merged