docs: update docs/ja
vuejs/vue-test-utils pull request #394
Opened 2018-01-29 13:01 UTC by 38elements

2018-01-29 16:55 UTC, kazupon requested changes
レビュー 👀 コメント 💬 しました。
確認お願いします。

2018-01-29 16:55 UTC, kazupon commented on docs/ja/guides/testing-SFCs-with-karma.md
> +ファイルを Webpack で前処理する必要があります。そのために、 Webpack をプレプロセッサとして加えます。そして、 Webpack の設定を含めます。プロジェクトに元々あった Webpack の設定ファイルを変更なしで使用することができます。
`preprocessor`は`プリプロセッサ`の訳が一般的なような気がします。

2018-01-29 16:55 UTC, kazupon commented on docs/ja/guides/testing-SFCs-with-karma.md
> +この設定では、 Chrome でテストを実行します。他のブラウザーを加える方法は [Karma のドキュメントにある Browsers セクション](http://karma-runner.github.io/2.0/config/browsers.html) を見てください。
`ブラウザ`という訳が一般的なような気がします。

2018-01-29 16:55 UTC, kazupon commented on docs/ja/guides/testing-SFCs-with-karma.md
> +<template>
SFCの`<template>`ブロックのインデントが気になりました。なるべく公式スタイルガイドに合わせて一貫性をもたせた方がいいかなと思います。`en`などの他の言語も同様です。

2018-01-29 16:55 UTC, kazupon commented on docs/ja/guides/testing-SFCs-with-karma.md
> +環境変数の `BABEL_ENV` をセットするために `cross-env` を使います。テストをコンパイルする時に babel-plugin-istanbul を使用します。プロダクションコードをコンパイルする時は `babel-plugin-istnabul` を含めるべきではありません。
`babel-plugin-istanbul`が原文と異なりバッククォートされていないようです。

2018-01-30 12:50 UTC, 38elements commented
@kazupon 
レビューありがとうございます。
指摘していただいた点を修正しました。
よろしくお願いします。

2018-01-31 00:34 UTC, kazupon approved these changes

2018-02-03 11:18 UTC, merged