docs: add docs/ja/api/renderToString.md
vuejs/vue-test-utils pull request #446
Opened 2018-02-27 14:28 UTC by 38elements

2018-02-27 15:42 UTC, kazupon requested changes
レビュー 👀 コメント 💬 しました。
確認お願いします！

2018-02-27 15:42 UTC, kazupon commented on docs/ja/api/renderToString.md
> +        fooBar: FooBar, // Will match <slot name="FooBar" />,
コメントも翻訳しておくといいと思います。

2018-02-27 22:28 UTC, 38elements commented
@kazupon 
レビューありがとうございます。
指摘していただいた点を修正しました。
よろしくお願いします。

2018-02-27 23:51 UTC, 38elements commented
@kazupon 
レビューありがとうございます。
指摘していただいた箇所を修正しました。
よろしくお願いします。

2018-02-28 01:15 UTC, kazupon approved these changes

2018-02-28 06:58 UTC, eddyerburgh approved these changes
Thanks 😄 

Note that we're splitting this into a new package right now, so the docs will have to change a bit—https://github.com/vuejs/vue-test-utils/pull/447

2018-02-28 06:59 UTC, merged