docs: extend examples in find api (#473)
vuejs/vue-test-utils pull request #511
Opened 2018-04-02 20:32 UTC by igeligel

Regarding #473 i updated the documentation of the `.find(selector)` function. Whether the proposed API will be implemented, I guess the `.find(selector)` function stays the same more or less and documentation about getting a component should include all possibilities.

I included examples of every selector possible so people might see it. I also included some whitespace so the different types of selections are separated.

Thanks for the great project 👍

2018-04-02 23:11 UTC, 38elements commented
IMHO,
It seems that `name` option and `ref` option are the same.

2018-04-03 06:44 UTC, eddyerburgh requested changes

2018-04-03 06:44 UTC, eddyerburgh commented on docs/en/api/wrapper/find.md
> +const barRef = wrapper.find({ ref: 'bar' })
Can you  change this to a different value, like  `'foo'`

2018-04-03 16:58 UTC, igeligel commented on docs/en/api/wrapper/find.md
> +const barRef = wrapper.find({ ref: 'bar' })
I renamed this now to `foo` but I guess it is somehow confusing.

2018-04-08 15:04 UTC, eddyerburgh approved these changes
Thanks 😀

2018-04-08 15:04 UTC, merged