Render props on auto stubs
vuejs/vue-test-utils pull request #834
Opened 2018-07-19 11:06 UTC by Akryum

closes #708

2018-07-19 12:33 UTC, eddyerburgh requested changes
Great :) 

Can you add a test please?

2018-07-28 09:16 UTC, eddyerburgh commented
I'll add a test :)

Do you have an example of a component where this.$attrs should be rendered?

2018-07-29 08:28 UTC, eddyerburgh approved these changes

2018-07-29 08:29 UTC, merged

2018-07-30 18:45 UTC, Shoroh commented
You are my heroes, guys! 👍