docs: update docs/ru
vuejs/vue-test-utils pull request #907
Opened 2018-08-07 23:39 UTC by lex111

@Alex-Sokolov review this please.

2018-08-08 09:52 UTC, Alex-Sokolov requested changes

2018-08-08 09:52 UTC, Alex-Sokolov commented on docs/ru/guides/using-with-typescript.md
> +$ npm install -g @vue/cli-service-global
Command for installing vue-cli?

2018-08-08 09:52 UTC, Alex-Sokolov commented on docs/ru/guides/using-with-typescript.md
> +В командной строке выберите `Manually select features`, выберите `TypeScript` и нажмите клавишу ввода. Это создаст проект с уже настроенным для работы с TypeScript.
С уже настроенным для работы TypeScript

2018-08-08 09:52 UTC, Alex-Sokolov commented on docs/ru/guides/using-with-typescript.md
> +Jest — это исполнитель тестов, разработанный Facebook, целью которого является поставка обширного решения для модульного тестирования. Вы можете узнать больше о Jest на его [официальной документации]
Вроде везде пишем "программа для запуска тестов"

2018-08-08 09:52 UTC, Alex-Sokolov commented on docs/ru/guides/using-with-typescript.md
> +Jest — это исполнитель тестов, разработанный Facebook, целью которого является поставка обширного решения для модульного тестирования. Вы можете узнать больше о Jest на его [официальной документации]
"поставка обширного решения" как-то не айс

2018-08-08 09:52 UTC, Alex-Sokolov commented on docs/ru/guides/using-with-typescript.md
> +Затем определите скрипт `test:unit` в `package.json`.
определите команду в scripts

2018-08-08 09:52 UTC, Alex-Sokolov commented on docs/ru/guides/using-with-typescript.md
> +Теперь у нас есть проект, пришло время написать единичный тест.
пришло время написать тест

2018-08-08 10:01 UTC, lex111 commented on docs/ru/guides/using-with-typescript.md
> +Jest — это исполнитель тестов, разработанный Facebook, целью которого является поставка обширного решения для модульного тестирования. Вы можете узнать больше о Jest на его [официальной документации]
> Jest is a test runner developed by Facebook, aiming **to deliver a battery-included unit testing solution**. 

Какие варианты это по-другому перевести?

2018-08-08 13:12 UTC, Alex-Sokolov commented on docs/ru/guides/using-with-typescript.md
> +Jest — это исполнитель тестов, разработанный Facebook, целью которого является поставка обширного решения для модульного тестирования. Вы можете узнать больше о Jest на его [официальной документации]
направленный на предоставление многофункционального решения для модульного тестирования например

2018-08-08 13:12 UTC, Alex-Sokolov approved these changes

2018-08-08 13:16 UTC, lex111 commented on docs/ru/guides/using-with-typescript.md
> +Jest — это исполнитель тестов, разработанный Facebook, целью которого является поставка обширного решения для модульного тестирования. Вы можете узнать больше о Jest на его [официальной документации]
Круто, как и всегда! :+1:

2018-08-08 13:17 UTC, lex111 commented
@eddyerburgh accept this PR please.

2018-08-10 15:54 UTC, lex111 commented
friendly ping to @eddyerburgh

2018-08-11 08:06 UTC, eddyerburgh approved these changes
Thanks for the work guys :)

2018-08-11 08:06 UTC, merged